; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;d
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[env]
platform = ststm32
board = genericSTM32F103C8
framework = stm32cube

lib_deps = https://github.com/berknylm/NMEA.git
debug_tool = stlink

force_verbose = True

[env:DEBUG]
build_type = debug

[env:RELEASE]
;build_type = release
build_unflags = -Os
build_flags = -O1

[env:RELEASE_9ma]
build_unflags = -Os
build_flags = -O0
